### ISSUE TITLE
Fix the monoid instance

### ISSUE THREAD

**Issue by harendra-kumar** [ppelleti/normalization-insensitive#1]
The [monoid instance](https://github.com/ppelleti/normalization-insensitive/blob/7a4b595f2d7fd9cf3356f09ca72ced862c2c46b6/Data/Unicode/NormalizationInsensitive/Internal.hs#L115) is not correct. The concatenation of two normalized strings is not guaranteed to be normalized. The easiest but inefficient solution is to normalize the concatenated string again. We can switch to a more efficient solution in future.

See http://unicode.org/reports/tr15/#Concatenation and harendra-kumar/unicode-transforms#2 .

**Comment by mignon-p** [comment]
Thanks!  I've fixed the problem in the way you suggested.
