### ISSUE TITLE
On Hackage?

### ISSUE THREAD

**Issue by Blaisorblade** [ppelleti/normalization-insensitive#2]
Now that we have https://hackage.haskell.org/package/unicode-transforms, having this package on Hackage would help, especially for commercialhaskell/stack#1810.

**Comment by mignon-p** [comment]
Yes, that's the plan.  I have a candidate package at https://hackage.haskell.org/package/normalization-insensitive-2.0/candidate

@harendra-kumar gave me some good feedback on the candidate.  I plan on making the fixes soon, but just haven't had a chance yet.  But I'll try to get to it soon, upload a new candidate, and then if everyone's happy with it, I can release.

**Comment by mignon-p** [comment]
I've uploaded a new candidate at
https://hackage.haskell.org/package/normalization-insensitive-2.0.0.0/candidate

**Comment by harendra-kumar** [comment]
Looks good. 

As @Blaisorblade mentioned in the hackage bug you can try the following and keep your version as 2.0 (which sounds much better than 2.0.0.0):

> There actually is a button for "delete documentation and trigger rebuild" (click "edit package 
> information", then the package version under "Manage documentation", then "delete 
> documentation and trigger rebuild".)

**Comment by mignon-p** [comment]
Since I haven't received any more comments about the package, I've gone ahead and published version 2.0:
https://hackage.haskell.org/package/normalization-insensitive-2.0

Now that it is published, I've deleted the candidates.

**Comment by mignon-p** [comment]
Should I announce this new package on `haskell-cafe`, or some other mailing list?  This is my first package, so I don't know what the protocol is.

**Comment by harendra-kumar** [comment]
I think yes, it will be helpful to those who are looking for something like this. Otherwise people are left to discover it by themselves.
